name: WakaTime Stats in README

on:
  schedule:
    - cron: '0 0 * * *'  # Exécute tous les jours à minuit
  workflow_dispatch:  # Permet de lancer le workflow manuellement

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3  # Nécessaire pour cloner le dépôt

      - name: Update WakaTime Stats
        uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          SHOW_OS: "True"
          SHOW_PROJECTS: "True"
          SHOW_LANGUAGE_PER_REPO: "True"
